### ISSUE TITLE
[Graph] Dynamic workflows should be visualized in the UI

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyteconsole#295]
**Motivation: Why do you think this is important?**
It's not really helpful to see a generic node placeholder in the UI graph overview of a workflow. Sending the DJO spec would allow the UI to render the dynamic job graph.

**Goal: What should the final outcome look like, ideally?**
It should be possible to visualize dynamic workflow structure.

**Describe alternatives you've considered**
Not implementing this.

**[Optional] Propose: Link/Inline OR Additional context**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Comment by anrusina** [comment]
Already merged in, available from flyteconsole v.0.44.0
