### ISSUE TITLE
[Graph] Add support for any-depth nesting in graph UX

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#297]
**Motivation: Why do you think this is important?**
We want to add support for any-depth nesting on the Graph UX.  This is applicable for branching and sub-workflow/dynamic nodes.

Comps:
![Screen Shot 2021-09-23 at 9 36 47 AM](https://user-images.githubusercontent.com/84735036/134548137-a6e89048-dd75-4ce6-ae16-549d356c2646.png)

**Goal: What should the final outcome look like, ideally?**
Provide users a means to dive deep into nested graphs.

**Comment by anrusina** [comment]
Resolved, starting from flyteconsole v.0.44.0
