### ISSUE TITLE
Feat: Launch plan detail page

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#298]
### Motivation: Why do you think this is important?

Currently users cannot view the details of a launch plan without clicking to launch a new workflow/task and viewing the pre-populated inputs. To fix this we will create a new view, similar to flyteconsole currently handles workflows or task detail pages, that will show users the details of a launch plan spec. This will include a side nav item for Launch Plans and its accompanying search page. 

Additionally, once the LP detail page is complete we want to add details about which launch plan was used across the application (eg, when displaying lists of workflow/task executions, etc).

### Goal: What should the final outcome look like, ideally?
This ticket will track the overall effort but the work will be broken into tasks and managed by the new feature flag framework.

UX Comps: (Note: this may still change)
<img width="1082" alt="Screen Shot 2022-01-18 at 9 44 16 AM" src="https://user-images.githubusercontent.com/84735036/149990485-199b0594-6016-4f4a-abbe-46bf236908bc.png">
<img width="1096" alt="Screen Shot 2022-01-18 at 9 43 47 AM" src="https://user-images.githubusercontent.com/84735036/149990492-90d5a214-6d05-46b3-a8c4-d647887c2a68.png">
<img width="1099" alt="Screen Shot 2022-01-18 at 9 43 57 AM" src="https://user-images.githubusercontent.com/84735036/149990498-5f0b01ab-39ee-42a2-8264-74e98c9bca21.png">
<img width="1084" alt="Screen Shot 2022-01-18 at 9 44 03 AM" src="https://user-images.githubusercontent.com/84735036/149990504-7eddbe0b-4afb-49b6-a1e9-7d51900167bb.png">

Flyteconsole users can view:
 - View which launch plan was used for an execution with a truncated name for:
   - workflow executions
   - task executions
   - executions
 - View default launch plan metadata for a given workflow.
 - View all schedules currently bound to a workflow
 - In all lists where we display these links, we need to add a filter for launch plans
    - Filter includes input/string search
    - Five most recent launch plans 
   
Launch plan detail page:
 - Displays all default values for a launch plan
 - Displays schedule (if exists)
 - Displays lazy-loading list (like workflow/task detail pages) of all executions that used that launch plan.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by anrusina** [comment]
Additional context:

Launch plan data can be found in two places:
Expected Inputs are found in the closure: https://docs.flyte.org/projects/flyteidl/en/latest/protos/docs/admin/admin.html#ref-flyteidl-admin-launchplanclosure%7CLaunchPlanClosure

Fixed Inputs are found in the spec:
https://docs.flyte.org/projects/flyteidl/en/latest/protos/docs/admin/admin.html#ref-flyteidl-admin-launchplanspec%7CLaunchPlanSpec

**Comment by anrusina** [comment]
**Info needed from BE:**

It looks that we can use [api/v1/launch_plans/cluster-deploy/development?&limit=50](https://demo.nuclyde.io/api/v1/launch_plans/cluster-deploy/development?&limit=50) - to get the list of all the Launch plans, but it looks like it return all versions of all Launch plans.

- Is there an API call to get all unique LaunchPlans without taking into account version.  So there will be one entry for the launch plan which has two versions
- Is there an API to get list of all version for a specific LaunchPlan (similar to [Workflows API](https://demo.nuclyde.io/api/v1/workflows/flytesnacks/development?filters=eq(workflow.name,athena.athena.no_io_wf)&token=&limit=10))
- Is there an API to get list of executions for current LaunchPlan and is it possible to filter by LaunchPlan version? ( I assume we still would be able to filter them as any other executions, by duration and archive status)

**Comment by cosmicBboy** [comment]
this has been done for a while
