### ISSUE TITLE
[Graph]the node name for the sub-graph should be shown

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyteconsole#299]
**Motivation: Why do you think this is important?**
currently the graph view shows only the subgraph as a dotted border, but does not show the name of he subgraph containing node. It would be useful to show this name

**Goal: What should the final outcome look like, ideally?**
The friendly name should be shown within the dotted subsection

example of graph that does not show the node id
![Screen Shot 2021-09-27 at 6 23 23 PM](https://user-images.githubusercontent.com/16888709/135006885-ad23efcd-7727-4e5b-a618-788c05d28703.png)

**Comment by anrusina** [comment]
verify when Jason's Graphs update would be released

**Comment by anrusina** [comment]
Already supported from flyteconsole v.0.44.0
<img width="507" alt="Screen Shot 2022-04-12 at 2 57 16 PM" src="https://user-images.githubusercontent.com/55718143/163061612-1e81bed3-e129-4135-b3e8-80a8b97c1e26.png">
