### ISSUE TITLE
[Graph] The graph view should show, if a node was cached

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyteconsole#300]
**Motivation: Why do you think this is important?**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] OR why this would be a cool addition OR which usecases could this unblock.

**Goal: What should the final outcome look like, ideally?**
A clear and concise description of what you want to happen or achieve.

The graph view does   not show if the outputs were retrieved from cache of if the results were cached, as shown in this example
![Screen Shot 2021-09-27 at 6 23 23 PM](https://user-images.githubusercontent.com/16888709/135006973-a4cb6d03-755c-46cf-819f-46e35883de05.png)

But, the node list view shows it
![Screen Shot 2021-09-27 at 6 23 14 PM](https://user-images.githubusercontent.com/16888709/135006987-c25c4e69-61fe-4a7d-885b-f3fd081c506a.png)

**Comment by hongxunjin** [comment]
@olga-union I agree with your suggestion of integrating the cache read and cache write icon inside the container of the graph, being consistent with the timeline view. And here is the mockup screens. 
<img width="1756" alt="Cached node for graph" src="https://user-images.githubusercontent.com/89930731/163789925-16279f77-18b6-4322-aa4d-745a8ebcbbdd.png">

**Comment by anrusina** [comment]
Fixed with flyteconsole version 0.54.0
