### ISSUE TITLE
[BUG] Relaunch with modified security context doesn't take effect

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyteconsole#304]
### Describe the bug

I've an execution that was originally launched with a Kubernetes Service Account. I later realized this was wrong, so I went to the UI and hit "Relaunch" and then down under the "Advanced Options" I cleared the text box "Kubernetes Service Account" and hit "Relaunch". This, unfortunately didn't take effect and the new execution was still launched with the same old Kubernetes Service Account.

### Expected behavior

When cleared, it should propagate that in the execution creation request.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by anrusina** [comment]
Need to re-check after #372 would be fixed. Looks like this bug is already fixed.
Tried it on 
https://demo.nuclyde.io/console/projects/cluster-deploy/domains/development/workflows/workflows.driver.create_org?duration=all

**Comment by jsonporter** [comment]
I was able to confirm this; the execution is called with the correct value and the execution header reflects this correct value however I can confirm that "relaunch" does not persist this change. This ticket will track the fix: https://github.com/flyteorg/flyteconsole/issues/496
