### ISSUE TITLE
[Timeline] Cached items should have a visual representation in timeline

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#331]
### Motivation

Currently if a specific node execution output was taken from previously cached result the Timeline view has a fully empty raw for such task. We can identify node as cashed only by opening NodeDetails panel

[Example workflow](https://demo.nuclyde.io/console/projects/cluster-deploy/domains/development/executions/vxymfr417g?duration=all)
<img width="1319" alt="Screen Shot 2022-03-16 at 11 01 37 AM" src="https://user-images.githubusercontent.com/55718143/158658095-f161cfa2-8fda-46a0-87e1-903a14f08e9e.png">

Mainly it is happening because for such task we do not have start / end time information. We only have field last updated, which can point to any day in the past.

Theoretically we can use parent start / end time in such case. However it would be nice too if we won't be limited by requesting parent node execution info

### Goal 

User should easily see if the node execution was cached.

**Comment by hamersaw** [comment]
@anrusina we may be able to add some metadata to the task in FlytePropeller if necessary (ex. cache hit time). Happy to have a conversation.

**Comment by anrusina** [comment]
@hamersaw I currently would rely on checking `closure.taskNodeMetada.cachedStatus` and if it has value CatalogCacheStatus.CACHE_HIT I will calculate time duration as (updatedAt - createdAt) value.
Is this sound reasonable?

**Comment by hamersaw** [comment]
@anrusina Yeah, let's go with that for now. I think in the case of a cache hit there may only be a single event sent. So my concern is that updateAt and createdAt are going to be the same time.
