### ISSUE TITLE
Bug: Investigate potential memory leak

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#342]
Users have reported a potential memory leak in flyteconsole after docker reported OOM ("out of memory") errors as well as the container memory increasing each time the page is refreshed.

Slack (internal) conversation: https://unionai.slack.com/archives/C01H0FN1NJX/p1648020013623039

<img width="587" alt="Screenshot 2022-03-23 at 5 13 23 PM" src="https://user-images.githubusercontent.com/84735036/159741561-129a663a-4d77-400d-beaf-9da92980660c.png">

1. Establish if this is a memory leak or if the application simply needs more memory.
2. Submit fix if memory leak is found.

**Comment by anrusina** [comment]
Current investigation show that spike in memory usage is connected to `babel` and `node` updates. The old webpack4 wasn't able to properly shake the dependency tree after babel was updated and resulted in a bigger memmory consumption.
Flyte v.0.19.3 includes flyteconsole v.0.43.0 under the hood.

The issue usually presented itself as  following error: `upstream connect error or disconnect/reset before headers. reset reason: connection termination`, when user opens  http://localhost:30081/console 

To solve the issue one of the next things could be used:
1.  You can start sandbox using `--version` flag 
```
flytectl sandbox start --source . --version v0.19.2
// OR
flytectl sandbox start --version v.0.19.2
```
2. You can increase flyteconsole pod memory:
```
// see all current running pods:
kubectl get pods -n flyte
// get information about current pod states - replace flyteconsole with yours pod name
kubectl describe pod -n flyte flyteconsole-7c9b6dc4fd-2d7m7
// edit deployment to increase memory limit - we increased to 500Mi
kubectl edit deployment/flyteconsole -n flyte   
```
3. Start flyte locally and update flyteconsole version using helm. For this one you need flyteorg/flyte repository locally and helm installed (`brew indstall helm`)
```
flytectl sandbox start 
// from flyte/charts/flyte
helm dependency build
// Update tag to fltyconsole image in charts/flyte/values.yaml to 0.42.1
// Disable Cluster resource manager as `cluster_resource_manager: enabled false`
helm upgrade -n flyte -f values.yaml --create-namespace flyte .
```

**Comment by anrusina** [comment]
To be clear there is no memory leak, Out of memory (OOM) exception happens due to initial bigger(not optimal) size of the pod.

Current memory measurements for flyteconsole:
```
Version       |   Memory on initialization
0.42.0        |          194 Mi
0.43.0        |          245 Mi
0.45.0        |          196 Mi
0.47.0        |          221 Mi
0.47.1        |          195 Mi
```
We need to do one more update to minimize package fluctuations in size.
We would keep an eye on package sizes.

**Comment by anrusina** [comment]
Issue is currently closed a separate work needed to optimize our webpack build: remove dead code; exclude storybook, mock and test files from build, etc. Separate task would be opened in nearest time.
