### ISSUE TITLE
Update flyte.org content

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#348]
(WIP)

We want to create a new feature-gallery (slides as content areas) to showcase the ease of using flyte. Initially it will have 5 slides (copy will be provided) and each slide will contain a title, a subtext and a video. Users should be able to scroll/click through the slides.

- Slide content: title, subtext, movie
- Should support clicking/scrolling through slides
- Videos should autostart on view and loop from there
- Should support {n} slides/updates

**Comment by anrusina** [comment]
This work was related to flyte.org site update. It's work currently done. 
Anyway it has a separate repository connected to it, so issue is closed here.
