### ISSUE TITLE
[DAG v2] The specific dynamic workflow doesn't show child tasks in Graph and in Timeline

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#375]
## Issue

Some of the dynamic workflows aren't showing as such in Graphic and Timeline view. 
Example: 
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/ejln5s2l03?duration=all

Observe:
- Node tab includes childs under `my_subwf`
- Graph and timeline show it up as a regular python task

Most probably the issue is connected to DagV2 parsing.

## Goal

Show al child tasks in Timeline and Graph view

**Comment by cosmicBboy** [comment]
fixed by #676
