### ISSUE TITLE
[Graph]For specific Workflow Version Graph view shows 404 error

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#379]
### Issue

For one specific workflow version a 404 is shown for Graph views .

Repro steps.
- Open https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/f536157ef1e4f459c84d?duration=all

Obesrve:
- Navigate to - > View All workflow versions  and try to select `lC0y/z2YQl3FJ5qO7c441w==`
- Filter executions by `lC0y/z2YQl3FJ5qO7c441w==` version, open execution and navigate to Graph tab

<img width="1094" alt="Screen Shot 2022-04-13 at 1 27 01 PM" src="https://user-images.githubusercontent.com/55718143/163265639-7dc25f70-4e55-448d-8115-6e9595bfdade.png">

### Goal

There are few possible solutions, the one should be picked depending on why issue happens.

If Workflow version data is not accessible /valid (not present any more):
 - hide it from versions list
OR
 - a more relevant message with error/ info would be shown

If Workflow Version could be accessed:
- EnsureThe workflow version data would be rendered properly

**Comment by cosmicBboy** [comment]
fixed by https://github.com/flyteorg/flyteconsole/pull/715
