### ISSUE TITLE
[Improvement] Too many workflows initially loaded when person opens Workflows tab

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#385]
### Motivation

Update: this ticket will need to be part of a broader refactor https://github.com/flyteorg/flyteconsole/issues/385

Currently when person opens Workflow tab we immediately are requesting all workflows with the limit of 10000,
 and then to show `Last 10 executions` on each of returned workflow we perform executions call
<img width="507" alt="Screen Shot 2022-04-13 at 3 32 42 PM" src="https://user-images.githubusercontent.com/55718143/163281250-f05364cb-d75b-4064-b241-305bc666c358.png">

It leads to a lot of redundant calls, information from which user most probably won't even see.

### Solution

Request paginated workflow items for example by using:
`useWorkflowNameList` from `src/components/hooks/useNamedEntity.ts`, which already have limit set to 
```
limits.DEFAULT === 25
```

Load more items when user have already scrolled through have of the list.

**Comment by eugenejahn** [comment]
wonder should we have a loadmore button to load more data 
ex.
![image](https://user-images.githubusercontent.com/25038146/166007929-78f6b9a7-fad5-4c54-9bf6-f1f30520da90.png)
or 
we just autoload data once the users scroll though the list

**Comment by eugenejahn** [comment]
and should we also apply the logic for workflows to tasks too?

**Comment by cosmicBboy** [comment]
closing: need GraphQL refactor
