### ISSUE TITLE
[CleanUp] Flyteconsole cleanups task

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#393]
This task is created to cover set of clean-ups which don't have bug attached and mainky needed to support our code than to fix any issues.

This Ticket number should be mentioned in code as:
`TODO FC#393: what's need to be done` 
whenever cleanup is needed.

Current list of cleanups:
- [ ] Simplify `WorkflowTabs` usage in NodeExecutionDetailsPanelContent
- [ ] Remove inputs/outputs fields from `ExecutionData` interface, ensure that they are not used anymore
- [ ] Unify `showOnHoverClass` usage - move it to commonStyles, for both parent, and child style
- [ ] Move all **Core.** and **Admin.** enums to one file: `src/models/enums.ts` (could be found by `It's an ENUM exports` string)
- [ ] move `createWorkflowName` into src/components/Project/test/ProjectWorkflows.test.tsx

- [ ] Storybooks for all olf flyteconsole components should start with `Legacy/` path in stories location(eg. `const stories = storiesOf('Navigation/NavBar', module);`) to ensure that we now that the y should be reimplemented/updated up to new standart

**Comment by anrusina** [comment]
Check if it makes sense to keep this one:
```
// Shared measurement constants specified in grid units
// for use with `theme.spacing()`
export const sideNavGridWidth = 34;
export const maxContainerGridWidth = 153;
export const navbarGridHeight = 8;
export const contentMarginGridUnits = 2;
```

**Comment by anrusina** [comment]
- [ ] remove anything related to DeprecatedLiteralMapViewer

**Comment by cosmicBboy** [comment]
wont'fis: closing this: we pivoted away from this approach
