### ISSUE TITLE
[Graph][BUG] Unable to view all the workflow versions

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyteconsole#416]
When trying to view all the workflow versions, seeing the following error:

<img width="1345" alt="Screenshot 2022-04-21 at 7 13 52 PM" src="https://user-images.githubusercontent.com/27777173/164471999-4aaa6c62-0721-4b9d-adc9-738820465854.png">

**Comment by anrusina** [comment]
Example:
[https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/workflows/k[…]rk.dataframe_passing.my_smart_structured_dataset?duration=all](https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/workflows/k8s_spark.dataframe_passing.my_smart_structured_dataset?duration=all), you should be seeing the error.

**Comment by anrusina** [comment]
One more sample provided by Carina: https://demo.nuclyde.io/console/projects/flytetester/domains/development/workflows/core.intermediate.subworkflows.my_subwf?duration=all
