### ISSUE TITLE
[Graph] Bug: Workflow Versions Graph not centered

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#466]
When viewing workflow versions, the static graph that is rendered is not correctly centered/sized on initial load. We need to fix this so that the graph is centered and correctly sized/zoomed to fit into the container on initial load.

Example: 
https://demo.nuclyde.io/console/projects/cluster-deploy/domains/development/workflows/workflows.driver.create_org/version/4edd875cbe683f20023415de25c0cacd264f1f7e

<img width="1310" alt="Screen Shot 2022-05-16 at 12 09 47 PM" src="https://user-images.githubusercontent.com/84735036/168664932-a22fbfae-4754-4f2e-a322-063ed4490291.png">

**Comment by cosmicBboy** [comment]
fixed by #541
