### ISSUE TITLE
Release FlyteConsole 1.1.1

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#500]
Release 1.1.1:

- [ ] release flyteconsole 1.1.1 and set it as latest
- [ ] release flyteconsole-release 1.1.1 and set it to latest
- [ ] Add git tag to the latest PR
- [ ] Add release description for the tag and link to flyteconsole-release package
- [ ] Notify about new release in flyte slack general and flyteconsole channel.
- [ ] Add READme to docs about this release steps

**Comment by jsonporter** [comment]
Done.
