### ISSUE TITLE
Feat: Decouple graph from flyteconsole for use as a plugin.

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#522]
We would like to start decoupling useful components from flyteconsole so that those components can be used as plugins (eg, rendering a flyteconsole component within custom applications). To that end we want to decouple from flyteconsole to be a standalone plugin. 

Acceptance Critera:
 - Graph is imported as a plugin

**Comment by cosmicBboy** [comment]
won't fix
