### ISSUE TITLE
Bug: Graph does not always center on initial load

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#524]
The graph should auto-center and auto-size itself each time a user tries to view an execution graph however currently this intended behavior is sporadic (ie, sometimes this works, sometimes it doesn't).  This ticket will cover investigating and fixing this bug.

Acceptance Criteria:
 - Graph should always auto-size and auto-center when a user tries to view a graph.
 - Fix should cover static graphs (version view) as well

**Comment by olga-union** [comment]
fixed by https://github.com/flyteorg/flyteconsole/pull/541
