### ISSUE TITLE
Improvement: Refactor entity search

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#526]
Currently the entity search (workflows, tasks, launch plans, etc) is a simple string search that requires loading the full search space. We want to refactor this experience so that the search doesn't need to pre-fetch all entities and instead and submit a search query to the backend.

Related: https://github.com/flyteorg/flyteconsole/issues/385

**Comment by Ruchika30** [comment]
Can I take this up @jsonporter ??
