### ISSUE TITLE
Bug: Cannot read properties of undefined when expanding execution details for a sub-workflow 

### ISSUE THREAD

**Issue by MorpheusXAUT** [flyteorg/flyteconsole#535]
We're currently experiencing a similar issue as #505 - for some of our workflows (including multiple sub-workflows and dynamic tasks), expanding the execution details of an already completed sub-workflow leads to an error (same as shown in the other issue).

The following error is shown in the browser console: ![console error](https://i.imgur.com/fcr9XEA.png)

I've tried cherry-picking commit [d38b98b](https://github.com/flyteorg/flyteconsole/commit/d38b98b2d68700415224ad6c621d79e928fded01) from #506, however it seems like that doesn't actually fix our issue.

From quickly digging around and adding some basic debug logging, it seems like `literalsToLiteralValueMap` iterates over some of the tasks's input parameters and tries to look up their `type` using the workflow inputs (which in our case don't always match).

If necessary, I can try to provide a slimmed down workflow/sub-workflow/task to reproduce or the result of the `/node_executions` and `/data/node_executions` `flyteadmin` calls.

**Comment by james-union** [comment]
@MorpheusXAUT Please share the workflow/sub-workflow/task id to reproduce on demo cluster if possible

**Comment by MorpheusXAUT** [comment]
@james-union I'll try to get a slimmed down workflow we can run in a demo setup to reproduce the issue, will let you know :+1:

**Comment by MorpheusXAUT** [comment]
PR submitted, confirmed to fix the issue we're seeing in our deployments/workflows via a locally built version of `flyteconsole`.
