### ISSUE TITLE
UI Bug: List of executions UI messes up after a particular task is aborted

### ISSUE THREAD

**Issue by shivaylamba** [flyteorg/flyteconsole#559]
![image](https://user-images.githubusercontent.com/19529592/183583017-195fe5da-fbec-4232-869b-e93bd34e981d.png)
Whenever a task is aborted and if we look at the list of executions, there is a UI bug and the list of executions messes up. This gets resolved after refreshing the screen

**Comment by cosmicBboy** [comment]
invalid
