### ISSUE TITLE
Signal: Add Signal resume resume view

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#587]
The signal resume modal window will render a single input (of any `Literal` type) that the user will enter to resume that node. The inputs should be the same as the launch window (ie, rendering with a type and empty-text helpers) and should validate in the same manner as the launch form.

Additionally, we should show the node's input. The comps are currently out of date but will soon be updated to no longer click-to-show and instead will always ben shown as json (in the same manner we display node inputs in the node execution detail panel).

![Screen Shot 2022-09-13 at 9 06 42 AM](https://user-images.githubusercontent.com/84735036/189953048-72afacfd-8aa4-4514-a16a-4a14bd06a954.png)

Note: will update comps but now render inputs as in execution details panel
![Screen Shot 2022-09-13 at 9 14 24 AM](https://user-images.githubusercontent.com/84735036/189953457-18cfb91b-39d3-4345-80bb-2998ab352050.png)

Requirements:
 - Correctly rendering input (same as launch form)
 - Validates input
 - Displays node's input

**Comment by cosmicBboy** [comment]
this should be addressed already by #622
