### ISSUE TITLE
Feat: Change Graph UI to display subworkflow nodes differently.

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#597]
Users have said that the current graph UI that shows nested/subworkflows as a solid grey is confusing - it does not show the phase of the (parent) execution and its not clear that its a subworkflow.

We want to change this so that:
 - Subworkflow node (collapsed) color reflects it's phase
 - Subworkflow node (collapsed) is not solid and instead has a border; border style is TBD.

**Comment by tanishk-23** [comment]
@jsonporter Can you assign this issue to me?
