### ISSUE TITLE
Improve project domain level workflow execution config display

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyteconsole#608]
# Project Level Settings (Temporary patch)
## Current state
Currently console does a get request on the project domain level workflow execution attributes (`http://localhost:8088/api/v1/project_domain_attributes/flytesnacks/staging?resource_type=6` for example).  If something is found, it shows this
![image](https://user-images.githubusercontent.com/2896568/193644417-c803a449-5be6-4b19-a65a-d5a688bbc6aa.png)

## Change
We would like to change it so that it also runs this request:
```
http://localhost:8088/api/v1/project_attributes/flytesnacks?resource_type=6
```
This request is special because unlike the higher specificity requests (like the project-domain one above and project/domain/workflow/lp requests), this endpoint will also merge in and return settings from Admin's system level configuration.  This is helpful for the user.

This ticket is to add a call to that endpoint, and merge in the existing call, with the existing project-domain call taking higher priority of course.  Keep in mind that you should do a deep check on objects.  That is, if the [security context](https://github.com/flyteorg/flyteidl/blob/5daa90176ad73fe1bd8b0cb8d7db62bdfae912d7/protos/flyteidl/admin/matchable_resource.proto#L110) object is there, but both [role and service account](https://github.com/flyteorg/flyteidl/blob/5daa90176ad73fe1bd8b0cb8d7db62bdfae912d7/protos/flyteidl/core/security.proto#L64-L67) are empty strings, then don't use it ofc.

See https://github.com/flyteorg/flyte/issues/2322 for the backend changes and more information, but keep in mind the information on there is also a bit confusing because there is a longer term project described in that issue.

**Comment by cosmicBboy** [comment]
fixed by https://github.com/flyteorg/flyteconsole/pull/689
