### ISSUE TITLE
Bug: when ENABLE_GA is unset Google Analytics is still enabled

### ISSUE THREAD

**Issue by rtkgeoff** [flyteorg/flyteconsole#614]
If you run flyteconsole without setting the ENABLE_GA env var, google analytics will still be enabled in the frontend.

I think this is caused by:
- defaulting the value to a boolean `false` instead of a string `'false'` [here](https://github.com/flyteorg/flyteconsole/blob/1386b4078aab83096d4de71e20a937ab8408d7d5/packages/zapp/console/env.js#L39)
- passing that value through to the frontend with no conversion to string [here](https://github.com/flyteorg/flyteconsole/blob/1386b4078aab83096d4de71e20a937ab8408d7d5/packages/zapp/console/env.js#L59) and [here](https://github.com/flyteorg/flyteconsole/blob/1859cf5ca8fc3000bec9f513dee517264846c08f/packages/zapp/console/src/server.ts#L27)
- comparing with `ENABLE_GA !== 'false'` in the frontend [here](https://github.com/flyteorg/flyteconsole/blob/1859cf5ca8fc3000bec9f513dee517264846c08f/packages/zapp/console/src/client.tsx#L17)

Note that the flyte helm chart will not set ENABLE_GA when [flyteconsole.ga.enabled is false](https://github.com/flyteorg/flyte/blob/4f73dc6994dfeafb9eecd9b17d16d7f9275b577a/charts/flyte-core/templates/console/deployment.yaml#L36-L42), so at least the helm chart is written assuming that not setting the env var should disable the feature.

**Comment by bkjain655** [comment]
Hi @rtkgeoff ,

I can work on this issue for Hacktoberfest. Can you please assign it to me?

**Comment by rtkgeoff** [comment]
@bkjain655 I don't believe I can assign it. Maybe ask in the flyte slack and someone with more permissions should be able to.

**Comment by flixr** [comment]
Any updates here?

**Comment by HiromuHota** [comment]
I've also had this issue. Any update or any workaround?

**Comment by jsonporter** [comment]
Fix merged 👍 
https://github.com/flyteorg/flyteconsole/pull/640
